// @ts-nocheck
import React, { useState, useMemo } from 'react';
import { dataSources } from '../data/sources';
import { fieldMatrix } from '../data/fields';
import { guardPolicies } from '../data/guardPolicies';
import { routingBlueprints } from '../data/routing';
import { securityDetections as secDetData } from '../data/securityDetections';
import { observabilityDetections as obsDetData } from '../data/observabilityDetections';
import { enrichments as enrichmentDataAll } from '../data/enrichments';

const card: React.CSSProperties = {
  background: 'var(--cds-color-bg)', border: '1px solid var(--cds-color-border-subtle)',
  borderRadius: 'var(--cds-radius-lg)', padding: 20, boxShadow: 'var(--cds-shadow-sm)',
};

const tag = (bg: string, color: string): React.CSSProperties => ({
  display: 'inline-block', padding: '2px 8px', borderRadius: 'var(--cds-radius-sm)',
  fontSize: 'var(--cds-font-size-xs)', fontWeight: 500, background: bg, color,
});

const selectStyle: React.CSSProperties = {
  padding: '8px 12px', border: '1px solid var(--cds-color-border)',
  borderRadius: 'var(--cds-radius-md)', fontSize: 'var(--cds-font-size-sm)',
  background: 'var(--cds-color-bg)', color: 'var(--cds-color-fg)',
};

const btnPrimary: React.CSSProperties = {
  padding: '10px 20px', border: 'none', borderRadius: 'var(--cds-radius-md)',
  fontSize: 'var(--cds-font-size-sm)', fontWeight: 600, cursor: 'pointer',
  background: 'var(--cds-brand-teal)', color: '#fff',
};

const btnSecondary: React.CSSProperties = {
  padding: '8px 16px', border: '1px solid var(--cds-color-border)', borderRadius: 'var(--cds-radius-md)',
  fontSize: 'var(--cds-font-size-sm)', fontWeight: 500, cursor: 'pointer',
  background: 'var(--cds-color-bg)', color: 'var(--cds-color-fg)',
};

const codeBlock: React.CSSProperties = {
  background: 'var(--cds-color-bg-muted)', border: '1px solid var(--cds-color-border-subtle)',
  borderRadius: 'var(--cds-radius-md)', padding: 16, fontFamily: 'var(--cds-font-mono)',
  fontSize: 'var(--cds-font-size-xs)', lineHeight: 1.6, overflow: 'auto', maxHeight: 400,
  whiteSpace: 'pre-wrap', color: 'var(--cds-color-fg)',
};

function downloadBlob(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

const allSources = dataSources.flatMap((c: any) => c.sources).filter((s: any) => s.status === 'available');

function generateStreamPack(sourceId: string, sourceName: string, fields: any[], guardPolicy: any, routing: any): string {
  const droppableFields = fields.filter(f => f.canDrop === 'Yes').map(f => f.field);
  const maskableFields = fields.filter(f => (f.canMask === 'Yes' || f.canMask === 'Sometimes') && f.guardAction === 'Mask').map(f => f.field);
  const redactFields = fields.filter(f => f.guardAction === 'Redact').map(f => f.field);
  const securityFields = fields.filter(f => f.securitySiem === 'Yes').map(f => f.field);
  const obsFields = fields.filter(f => f.observability === 'Yes' || f.observability === 'Sometimes').map(f => f.field);

  let yaml = '';
  yaml += `# ============================================================\n`;
  yaml += `# Cribl Stream Pipeline: ${sourceName}\n`;
  yaml += `# Generated by Dual-Use Bundles App\n`;
  yaml += `# ============================================================\n`;
  yaml += `#\n`;
  yaml += `# WHAT THIS DOES:\n`;
  yaml += `#   This pipeline optimizes ${sourceName} events for cost-efficient\n`;
  yaml += `#   routing. It drops low-value fields, masks sensitive data for\n`;
  yaml += `#   compliance, and prepares events for intelligent routing to\n`;
  yaml += `#   SIEM (reduced) and Lake (full-fidelity).\n`;
  yaml += `#\n`;
  yaml += `# HOW TO USE:\n`;
  yaml += `#   1. In Cribl Stream, go to Processing > Packs\n`;
  yaml += `#   2. Click "Add Pack" > "Import from File"\n`;
  yaml += `#   3. Upload this .yml file (or paste into a new pipeline)\n`;
  yaml += `#   4. Attach the pipeline to your ${sourceName} route\n`;
  yaml += `#   5. Preview with sample data before enabling in production\n`;
  yaml += `#\n`;
  yaml += `# HOW TO CUSTOMIZE:\n`;
  yaml += `#   - To KEEP a field that's being dropped: remove it from the\n`;
  yaml += `#     Eval function's "remove" list in Section 1\n`;
  yaml += `#   - To DROP additional fields: add them to the "remove" list\n`;
  yaml += `#   - To CHANGE masking behavior: edit the Mask function in\n`;
  yaml += `#     Section 2 (change matchRegex or method)\n`;
  yaml += `#   - To SKIP Guard entirely: delete or disable Section 2\n`;
  yaml += `#   - To ADJUST routing: modify the filter expressions in\n`;
  yaml += `#     Section 3's Route function\n`;
  yaml += `#\n`;
  yaml += `# FIELDS ANALYSIS:\n`;
  yaml += `#   Total fields: ${fields.length}\n`;
  yaml += `#   Droppable: ${droppableFields.length} (${fields.length > 0 ? Math.round(droppableFields.length / fields.length * 100) : 0}%)\n`;
  yaml += `#   Security SIEM required: ${securityFields.length}\n`;
  yaml += `#   Observability required: ${obsFields.length}\n`;
  yaml += `#   Guard protected: ${maskableFields.length + redactFields.length}\n`;
  yaml += `# ============================================================\n\n`;

  yaml += `id: ${sourceId}_optimization\n`;
  yaml += `name: "${sourceName} - Optimization Pipeline"\n`;
  yaml += `description: "Drop low-value fields, mask sensitive data, prepare for routing"\n`;
  yaml += `disabled: false\n`;
  yaml += `groups: {}\n\n`;
  yaml += `functions:\n\n`;

  // Section 1: Field Drops
  yaml += `  # ----------------------------------------------------------\n`;
  yaml += `  # SECTION 1: FIELD DROPS\n`;
  yaml += `  # Remove fields that add volume without analytical value.\n`;
  yaml += `  # These fields are safe to drop for both security and\n`;
  yaml += `  # observability use cases. If your workflow needs a field\n`;
  yaml += `  # listed here, simply remove it from the list below.\n`;
  yaml += `  # ----------------------------------------------------------\n`;
  if (droppableFields.length > 0) {
    yaml += `  - id: drop_low_value_fields\n`;
    yaml += `    filter: "true"\n`;
    yaml += `    disabled: false\n`;
    yaml += `    conf:\n`;
    yaml += `      remove:\n`;
    droppableFields.forEach(f => {
      yaml += `        - ${f}\n`;
    });
    yaml += `    description: "Remove ${droppableFields.length} low-value fields (debug, redundant, raw payloads)"\n`;
    yaml += `    # To keep a specific field: delete its line from the list above\n\n`;
  } else {
    yaml += `  # No droppable fields identified for this source.\n`;
    yaml += `  # All fields carry analytical value for at least one use case.\n\n`;
  }

  // Section 2: Guard / Masking
  yaml += `  # ----------------------------------------------------------\n`;
  yaml += `  # SECTION 2: DATA PROTECTION (Cribl Guard)\n`;
  yaml += `  # Mask or redact sensitive fields before they reach\n`;
  yaml += `  # destinations. This runs AFTER drops so Guard only\n`;
  yaml += `  # processes fields that survived Section 1.\n`;
  yaml += `  #\n`;
  if (guardPolicy) {
    yaml += `  # Compliance: ${guardPolicy.complianceFrameworks.join(', ') || 'General data governance'}\n`;
    yaml += `  # Estimated sensitive: ~${guardPolicy.estimatedSensitivePercent}% of fields\n`;
  }
  yaml += `  # ----------------------------------------------------------\n`;

  if (maskableFields.length > 0) {
    yaml += `  - id: guard_mask_pii\n`;
    yaml += `    filter: "true"\n`;
    yaml += `    disabled: false\n`;
    yaml += `    conf:\n`;
    yaml += `      rules:\n`;
    maskableFields.forEach(f => {
      yaml += `        - matchRegex: /.*/\n`;
      yaml += `          fieldName: ${f}\n`;
      yaml += `          method: mask\n`;
      yaml += `          # Replaces with ****. Change to 'hash' for reversible pseudonymization\n`;
    });
    yaml += `    description: "Mask ${maskableFields.length} fields containing PII (IPs, usernames, emails)"\n`;
    yaml += `    # To change masking method: replace 'mask' with 'hash' (SHA-256)\n`;
    yaml += `    # or 'encrypt' (reversible with key management)\n\n`;
  }

  if (redactFields.length > 0) {
    yaml += `  - id: guard_redact_secrets\n`;
    yaml += `    filter: "true"\n`;
    yaml += `    disabled: false\n`;
    yaml += `    conf:\n`;
    yaml += `      rules:\n`;
    redactFields.forEach(f => {
      yaml += `        - matchRegex: /.*/\n`;
      yaml += `          fieldName: ${f}\n`;
      yaml += `          method: redact\n`;
      yaml += `          # Completely removes value. Use for credentials, tokens, secrets\n`;
    });
    yaml += `    description: "Redact ${redactFields.length} fields containing secrets/credentials"\n`;
    yaml += `    # Redacted fields are irrecoverable — ensure you don't need the values\n\n`;
  }

  if (maskableFields.length === 0 && redactFields.length === 0) {
    yaml += `  # No fields flagged for masking/redaction in this source.\n\n`;
  }

  // Section 3: Routing Preparation
  yaml += `  # ----------------------------------------------------------\n`;
  yaml += `  # SECTION 3: ROUTING METADATA\n`;
  yaml += `  # Add a __destination field that downstream routes can use\n`;
  yaml += `  # to split traffic. This doesn't route by itself — it tags\n`;
  yaml += `  # the event so your Route table can filter on it.\n`;
  yaml += `  #\n`;
  yaml += `  # Routing strategy:\n`;
  yaml += `  #   - Security events (${securityFields.length} fields) → SIEM\n`;
  yaml += `  #   - Observability events (${obsFields.length} fields) → Obs platform\n`;
  yaml += `  #   - All events (full fidelity) → Cribl Lake\n`;
  yaml += `  # ----------------------------------------------------------\n`;
  yaml += `  - id: add_routing_metadata\n`;
  yaml += `    filter: "true"\n`;
  yaml += `    disabled: false\n`;
  yaml += `    conf:\n`;
  yaml += `      add:\n`;
  yaml += `        - name: __cribl_route\n`;
  yaml += `          value: "'lake'"\n`;
  yaml += `          # Default: everything goes to Lake. Override below for SIEM/Obs.\n`;
  yaml += `    description: "Tag events with routing metadata for downstream Route table"\n\n`;

  // Section 4: Summary Comment
  yaml += `# ============================================================\n`;
  yaml += `# NEXT STEPS AFTER IMPORT:\n`;
  yaml += `#\n`;
  yaml += `# 1. PREVIEW: Use Stream's "Preview" with sample ${sourceName}\n`;
  yaml += `#    data to verify field drops and masking look correct.\n`;
  yaml += `#\n`;
  yaml += `# 2. ROUTE TABLE: Create routes that filter on __cribl_route:\n`;
  yaml += `#    - Route to SIEM: filter "securityRelevant == true"\n`;
  yaml += `#    - Route to Obs: filter "obsRelevant == true"\n`;
  yaml += `#    - Route to Lake: default (catch-all)\n`;
  yaml += `#\n`;
  yaml += `# 3. TUNE: After 24-48h in production, check:\n`;
  yaml += `#    - Are any dropped fields needed? Add them back.\n`;
  yaml += `#    - Are masked fields breaking correlations? Use 'hash'\n`;
  yaml += `#      instead of 'mask' for consistent pseudonymization.\n`;
  yaml += `#    - Is the SIEM still receiving too much volume? Add more\n`;
  yaml += `#      fields to Section 1 or tighten Route filters.\n`;
  yaml += `#\n`;
  yaml += `# 4. GUARD AI (Optional): Enable Cribl Guard's AI model for\n`;
  yaml += `#    unstructured fields (message, description, command_line)\n`;
  yaml += `#    that may contain secrets not caught by pattern rules.\n`;
  yaml += `# ============================================================\n`;

  return yaml;
}

export default function ExportPage() {
  const [selectedSource, setSelectedSource] = useState(allSources[0]?.id || 'palo-alto-traffic');
  const [showPreview, setShowPreview] = useState(false);
  const [exportStatus, setExportStatus] = useState<string | null>(null);

  const source = allSources.find((s: any) => s.id === selectedSource);
  const sourceName = source?.name || selectedSource;
  const fields: any[] = (fieldMatrix as any)[selectedSource] || [];
  const guardPolicy = (guardPolicies as any)[selectedSource] || null;
  const routing = (routingBlueprints as any)[selectedSource] || null;

  const droppableCount = fields.filter(f => f.canDrop === 'Yes').length;
  const guardCount = fields.filter(f => f.guardAction && f.guardAction !== 'None').length;
  const secCount = fields.filter(f => f.securitySiem === 'Yes').length;
  const obsCount = fields.filter(f => f.observability === 'Yes' || f.observability === 'Sometimes').length;

  const packYaml = useMemo(() =>
    generateStreamPack(selectedSource, sourceName, fields, guardPolicy, routing),
    [selectedSource, sourceName, fields, guardPolicy, routing]
  );

  function handleDownloadPack() {
    downloadBlob(packYaml, `${selectedSource}-pipeline.yml`, 'text/yaml');
    setExportStatus('Pipeline YAML downloaded');
  }

  function handleCopyPack() {
    navigator.clipboard.writeText(packYaml).then(() => setExportStatus('Copied to clipboard'));
  }

  // Legacy export formats
  const [selectedSections, setSelectedSections] = useState<string[]>(['fields', 'securityDetections', 'observabilityDetections', 'routing', 'enrichments']);
  const sections = [
    { id: 'fields', name: 'Field Matrix', description: 'Field-by-field guidance for all destinations' },
    { id: 'securityDetections', name: 'Security Detections', description: 'Detection recommendations with required fields' },
    { id: 'observabilityDetections', name: 'Observability Detections', description: 'Observability detection recommendations' },
    { id: 'routing', name: 'Routing Blueprint', description: 'Data flow and destination strategy' },
    { id: 'enrichments', name: 'Enrichments', description: 'Stream-time and search-time enrichments' },
  ];
  function toggleSection(id: string) { setSelectedSections(prev => prev.includes(id) ? prev.filter(s => s !== id) : [...prev, id]); }

  function handleLegacyExport(format: string) {
    setExportStatus(null);
    const secDets = (secDetData as any)[selectedSource] || [];
    const obsDets = (obsDetData as any)[selectedSource] || [];
    const enrichments = (enrichmentDataAll as any)[selectedSource] || null;
    try {
      if (format === 'json') {
        const bundle: any = { source: selectedSource, exportedAt: new Date().toISOString() };
        if (selectedSections.includes('fields')) bundle.fields = fields;
        if (selectedSections.includes('securityDetections')) bundle.securityDetections = secDets;
        if (selectedSections.includes('observabilityDetections')) bundle.observabilityDetections = obsDets;
        if (selectedSections.includes('routing')) bundle.routing = routing;
        if (selectedSections.includes('enrichments')) bundle.enrichments = enrichments;
        downloadBlob(JSON.stringify(bundle, null, 2), `${selectedSource}-bundle.json`, 'application/json');
        setExportStatus('JSON bundle downloaded');
      } else if (format === 'csv-fields') {
        let csv = 'Field,Description,Security SIEM,Observability,Full Fidelity,Can Drop,Can Mask,Guard Action,Notes\n';
        fields.forEach((f: any) => { csv += `"${f.field}","${f.description}","${f.securitySiem}","${f.observability}","${f.fullFidelity}","${f.canDrop}","${f.canMask}","${f.guardAction || 'None'}","${f.notes}"\n`; });
        downloadBlob(csv, `${selectedSource}-field-matrix.csv`, 'text/csv');
        setExportStatus('CSV field matrix downloaded');
      } else if (format === 'detection-yaml') {
        let yaml = `# Detection YAML for ${sourceName}\n# Generated: ${new Date().toISOString()}\n\n`;
        const allDets = [...(selectedSections.includes('securityDetections') ? secDets : []), ...(selectedSections.includes('observabilityDetections') ? obsDets : [])];
        allDets.forEach((d: any) => {
          yaml += `- id: ${d.id}\n  name: "${d.name}"\n  objective: "${d.objective}"\n  severity: "${d.severity || d.category || ''}"\n`;
          if (d.mitre?.length > 0) { yaml += `  mitre:\n`; d.mitre.forEach((m: string) => { yaml += `    - "${m}"\n`; }); }
          yaml += `  required_fields:\n`; d.requiredFields.forEach((f: string) => { yaml += `    - ${f}\n`; });
          yaml += `  detection_logic: |\n    ${d.detectionLogic}\n\n`;
        });
        downloadBlob(yaml, `${selectedSource}-detections.yml`, 'text/yaml');
        setExportStatus('Detection YAML downloaded');
      }
    } catch { setExportStatus('Export failed — source may not have data for this format.'); }
  }

  return (
    <div>
      <div style={{ marginBottom: 24 }}>
        <h2 style={{ fontSize: 'var(--cds-font-size-xxl)', fontWeight: 600, color: 'var(--cds-color-fg)', marginBottom: 8 }}>Export</h2>
        <p style={{ fontSize: 'var(--cds-font-size-base)', color: 'var(--cds-color-fg-muted)', lineHeight: 1.6 }}>
          Generate ready-to-import Cribl Stream pipeline configs or export bundle data for stakeholder review.
        </p>
      </div>

      {/* Source selector */}
      <div style={{ display: 'flex', gap: 12, alignItems: 'center', marginBottom: 24 }}>
        <select value={selectedSource} onChange={e => { setSelectedSource(e.target.value); setShowPreview(false); setExportStatus(null); }} style={{ ...selectStyle, minWidth: 260 }}>
          {dataSources.map((cat: any) => (
            <optgroup key={cat.category} label={`${cat.icon} ${cat.category}`}>
              {cat.sources.map((s: any) => <option key={s.id} value={s.id}>{s.name}</option>)}
            </optgroup>
          ))}
        </select>
        <span style={tag('var(--cds-color-accent-subtle)', 'var(--cds-color-accent)')}>{sourceName}</span>
      </div>

      {/* ============ STREAM PACK GENERATOR ============ */}
      <div style={{ ...card, marginBottom: 32, border: '1px solid var(--cds-brand-teal)' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 16 }}>
          <span style={{ fontSize: 22 }}>&#x1F4E6;</span>
          <div>
            <h3 style={{ fontSize: 'var(--cds-font-size-lg)', fontWeight: 600, margin: 0 }}>Generate Stream Pipeline</h3>
            <p style={{ fontSize: 'var(--cds-font-size-sm)', color: 'var(--cds-color-fg-muted)', margin: 0 }}>
              Importable Cribl Stream pipeline with field drops, Guard masking, and routing metadata
            </p>
          </div>
        </div>

        {/* What you'll get */}
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 10, marginBottom: 20 }}>
          <div style={{ padding: 12, background: 'var(--cds-color-bg-subtle)', borderRadius: 'var(--cds-radius-md)', textAlign: 'center' }}>
            <div style={{ fontSize: 'var(--cds-font-size-xl)', fontWeight: 700, color: '#ef4444' }}>{droppableCount}</div>
            <div style={{ fontSize: 10, color: 'var(--cds-color-fg-muted)', marginTop: 2 }}>Fields Dropped</div>
          </div>
          <div style={{ padding: 12, background: 'var(--cds-color-bg-subtle)', borderRadius: 'var(--cds-radius-md)', textAlign: 'center' }}>
            <div style={{ fontSize: 'var(--cds-font-size-xl)', fontWeight: 700, color: '#a855f7' }}>{guardCount}</div>
            <div style={{ fontSize: 10, color: 'var(--cds-color-fg-muted)', marginTop: 2 }}>Guard Protected</div>
          </div>
          <div style={{ padding: 12, background: 'var(--cds-color-bg-subtle)', borderRadius: 'var(--cds-radius-md)', textAlign: 'center' }}>
            <div style={{ fontSize: 'var(--cds-font-size-xl)', fontWeight: 700, color: 'var(--cds-color-warning)' }}>{secCount}</div>
            <div style={{ fontSize: 10, color: 'var(--cds-color-fg-muted)', marginTop: 2 }}>SIEM Fields</div>
          </div>
          <div style={{ padding: 12, background: 'var(--cds-color-bg-subtle)', borderRadius: 'var(--cds-radius-md)', textAlign: 'center' }}>
            <div style={{ fontSize: 'var(--cds-font-size-xl)', fontWeight: 700, color: '#3b82f6' }}>{obsCount}</div>
            <div style={{ fontSize: 10, color: 'var(--cds-color-fg-muted)', marginTop: 2 }}>Obs Fields</div>
          </div>
        </div>

        {/* How it works explanation */}
        <div style={{ background: 'var(--cds-color-bg-subtle)', borderRadius: 'var(--cds-radius-md)', padding: 16, marginBottom: 20 }}>
          <div style={{ fontSize: 'var(--cds-font-size-xs)', fontWeight: 600, color: 'var(--cds-color-fg)', marginBottom: 10, textTransform: 'uppercase', letterSpacing: '0.5px' }}>What This Pipeline Does</div>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 12 }}>
            <div>
              <div style={{ fontSize: 'var(--cds-font-size-sm)', fontWeight: 600, color: '#ef4444', marginBottom: 4 }}>1. Drop Low-Value Fields</div>
              <div style={{ fontSize: 'var(--cds-font-size-xs)', color: 'var(--cds-color-fg-muted)', lineHeight: 1.5 }}>
                Removes {droppableCount} fields that add volume without analytical value (debug data, raw payloads, redundant metadata).
              </div>
            </div>
            <div>
              <div style={{ fontSize: 'var(--cds-font-size-sm)', fontWeight: 600, color: '#a855f7', marginBottom: 4 }}>2. Protect Sensitive Data</div>
              <div style={{ fontSize: 'var(--cds-font-size-xs)', color: 'var(--cds-color-fg-muted)', lineHeight: 1.5 }}>
                Masks/redacts {guardCount} fields containing PII, credentials, or infrastructure details for {guardPolicy?.complianceFrameworks?.join(', ') || 'compliance'}.
              </div>
            </div>
            <div>
              <div style={{ fontSize: 'var(--cds-font-size-sm)', fontWeight: 600, color: 'var(--cds-brand-teal)', marginBottom: 4 }}>3. Tag for Routing</div>
              <div style={{ fontSize: 'var(--cds-font-size-xs)', color: 'var(--cds-color-fg-muted)', lineHeight: 1.5 }}>
                Adds routing metadata so your Route table can split: {secCount} fields to SIEM, {obsCount} fields to Obs, full fidelity to Lake.
              </div>
            </div>
          </div>
        </div>

        {/* Import instructions */}
        <div style={{ background: 'var(--cds-color-bg-subtle)', borderRadius: 'var(--cds-radius-md)', padding: 16, marginBottom: 20 }}>
          <div style={{ fontSize: 'var(--cds-font-size-xs)', fontWeight: 600, color: 'var(--cds-color-fg)', marginBottom: 10, textTransform: 'uppercase', letterSpacing: '0.5px' }}>How to Import</div>
          <ol style={{ margin: 0, paddingLeft: 20, fontSize: 'var(--cds-font-size-sm)', color: 'var(--cds-color-fg-muted)', lineHeight: 2 }}>
            <li>Download the pipeline YAML below</li>
            <li>In Cribl Stream: <strong>Processing &gt; Pipelines &gt; Add Pipeline &gt; Import</strong></li>
            <li>Upload the <code>.yml</code> file — it creates the pipeline with all functions</li>
            <li>Attach the pipeline to your {sourceName} route (or create a new route)</li>
            <li>Use <strong>Preview</strong> with live/sample data to verify behavior before enabling</li>
          </ol>
        </div>

        {/* Customization guide */}
        <div style={{ background: 'var(--cds-color-bg-subtle)', borderRadius: 'var(--cds-radius-md)', padding: 16, marginBottom: 20 }}>
          <div style={{ fontSize: 'var(--cds-font-size-xs)', fontWeight: 600, color: 'var(--cds-color-fg)', marginBottom: 10, textTransform: 'uppercase', letterSpacing: '0.5px' }}>How to Customize</div>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12, fontSize: 'var(--cds-font-size-xs)', color: 'var(--cds-color-fg-muted)', lineHeight: 1.6 }}>
            <div><strong>Keep a dropped field:</strong> Remove it from the Eval function's "remove" list in Section 1.</div>
            <div><strong>Drop more fields:</strong> Add field names to Section 1's remove list.</div>
            <div><strong>Change mask to hash:</strong> In Section 2, replace <code>method: mask</code> with <code>method: hash</code> for reversible pseudonymization.</div>
            <div><strong>Skip Guard entirely:</strong> Disable or delete Section 2 functions.</div>
            <div><strong>Add custom routing logic:</strong> Edit Section 3's Eval to set <code>__cribl_route</code> based on event content.</div>
            <div><strong>Tune after deploy:</strong> Monitor for 24-48h, then adjust drops/masks based on actual pipeline metrics.</div>
          </div>
        </div>

        {/* Actions */}
        <div style={{ display: 'flex', gap: 12, alignItems: 'center' }}>
          <button onClick={handleDownloadPack} style={btnPrimary}>Download Pipeline YAML</button>
          <button onClick={handleCopyPack} style={btnSecondary}>Copy to Clipboard</button>
          <button onClick={() => setShowPreview(!showPreview)} style={btnSecondary}>{showPreview ? 'Hide Preview' : 'Preview YAML'}</button>
          {exportStatus && <span style={{ fontSize: 'var(--cds-font-size-sm)', color: 'var(--cds-brand-teal)', fontWeight: 500 }}>{exportStatus}</span>}
        </div>

        {/* YAML Preview */}
        {showPreview && (
          <div style={{ marginTop: 16 }}>
            <pre style={codeBlock}>{packYaml}</pre>
          </div>
        )}
      </div>

      {/* ============ OTHER EXPORT FORMATS ============ */}
      <div style={{ marginBottom: 24 }}>
        <h3 style={{ fontSize: 'var(--cds-font-size-lg)', fontWeight: 600, marginBottom: 16 }}>Other Export Formats</h3>

        <div style={{ marginBottom: 16 }}>
          <div style={{ fontSize: 'var(--cds-font-size-sm)', fontWeight: 600, marginBottom: 8 }}>Include Sections:</div>
          <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
            {sections.map(s => (
              <label key={s.id} style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '4px 10px', borderRadius: 'var(--cds-radius-md)', background: selectedSections.includes(s.id) ? 'var(--cds-color-accent-subtle)' : 'var(--cds-color-bg-muted)', cursor: 'pointer', fontSize: 'var(--cds-font-size-xs)' }}>
                <input type="checkbox" checked={selectedSections.includes(s.id)} onChange={() => toggleSection(s.id)} style={{ width: 14, height: 14, accentColor: 'var(--cds-brand-teal)' }} />
                {s.name}
              </label>
            ))}
          </div>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 12 }}>
          <div style={{ ...card, cursor: 'pointer' }} onClick={() => handleLegacyExport('json')}>
            <h4 style={{ fontSize: 'var(--cds-font-size-sm)', fontWeight: 600, marginBottom: 6 }}>JSON Bundle</h4>
            <p style={{ fontSize: 'var(--cds-font-size-xs)', color: 'var(--cds-color-fg-muted)', marginBottom: 8, lineHeight: 1.5 }}>Complete machine-readable bundle with all selected sections.</p>
            <span style={tag('var(--cds-color-accent-subtle)', 'var(--cds-brand-teal)')}>Automation</span>
          </div>
          <div style={{ ...card, cursor: 'pointer' }} onClick={() => handleLegacyExport('csv-fields')}>
            <h4 style={{ fontSize: 'var(--cds-font-size-sm)', fontWeight: 600, marginBottom: 6 }}>CSV Field Matrix</h4>
            <p style={{ fontSize: 'var(--cds-font-size-xs)', color: 'var(--cds-color-fg-muted)', marginBottom: 8, lineHeight: 1.5 }}>Spreadsheet-friendly field recommendations for stakeholders.</p>
            <span style={tag('var(--cds-color-accent-subtle)', 'var(--cds-color-accent)')}>Stakeholders</span>
          </div>
          <div style={{ ...card, cursor: 'pointer' }} onClick={() => handleLegacyExport('detection-yaml')}>
            <h4 style={{ fontSize: 'var(--cds-font-size-sm)', fontWeight: 600, marginBottom: 6 }}>Detection YAML</h4>
            <p style={{ fontSize: 'var(--cds-font-size-xs)', color: 'var(--cds-color-fg-muted)', marginBottom: 8, lineHeight: 1.5 }}>Sigma-compatible detection rules with MITRE tags.</p>
            <span style={tag('var(--cds-color-accent-subtle)', 'var(--cds-color-accent)')}>Sigma-Compatible</span>
          </div>
        </div>
      </div>
    </div>
  );
}
