import { apiUrl } from './cribl';

const DASHBOARD_BASE = () => `${apiUrl()}/m/default_search/search/dashboards`;

export interface DashboardPanel {
  id: string;
  title: string;
  query: string;
  description?: string;
  type: 'search';
  earliest: string;
  latest: string;
}

export interface Dashboard {
  id: string;
  name: string;
  description?: string;
  panels: DashboardPanel[];
}

export async function listDashboards(): Promise<Dashboard[]> {
  const base = DASHBOARD_BASE();
  if (!base) return [];
  const res = await fetch(base, { method: 'GET', headers: { 'Content-Type': 'application/json' } });
  if (!res.ok) return [];
  const data = await res.json();
  return data.items || data || [];
}

export async function createDashboard(dashboard: Dashboard): Promise<{ ok: boolean; status: number; message?: string }> {
  const base = DASHBOARD_BASE();
  const res = await fetch(base, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(dashboard),
  });
  if (res.ok) return { ok: true, status: res.status };
  const text = await res.text().catch(() => '');
  return { ok: false, status: res.status, message: text.substring(0, 300) };
}

export async function updateDashboard(id: string, dashboard: Dashboard): Promise<{ ok: boolean; status: number; message?: string }> {
  const base = DASHBOARD_BASE();
  const res = await fetch(`${base}/${id}`, {
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(dashboard),
  });
  if (res.ok) return { ok: true, status: res.status };
  const text = await res.text().catch(() => '');
  return { ok: false, status: res.status, message: text.substring(0, 300) };
}

export async function getDashboard(id: string): Promise<Dashboard | null> {
  const base = DASHBOARD_BASE();
  const res = await fetch(`${base}/${id}`, { method: 'GET', headers: { 'Content-Type': 'application/json' } });
  if (!res.ok) return null;
  return await res.json();
}

export function buildDashboards(
  sourceName: string,
  sourceId: string,
  dataset: string,
  secDetections: any[],
  obsDetections: any[],
  enabledSecIds: Set<string>,
  enabledObsIds: Set<string>,
): { security: Dashboard | null; observability: Dashboard | null } {
  const secDets = secDetections.filter(d => enabledSecIds.has(d.id));
  const obsDets = obsDetections.filter(d => enabledObsIds.has(d.id));

  const cleanId = (s: string) => s.replace(/[^a-zA-Z0-9_]/g, '_');

  let security: Dashboard | null = null;
  if (secDets.length > 0) {
    const panels: DashboardPanel[] = [];
    for (const det of secDets) {
      if (!det.criblSearchQueries) continue;
      for (const q of det.criblSearchQueries) {
        panels.push({
          id: cleanId(`sec_${det.id}_${panels.length}`),
          title: `${det.name} - ${q.name}`,
          query: q.query.replace(/\$DATASET/g, dataset),
          description: q.description || det.objective,
          type: 'search',
          earliest: '-24h',
          latest: 'now',
        });
      }
    }
    const dashId = cleanId(`dub_${sourceId}_security`);
    const dashName = `${sourceName} - Security`.replace(/[^a-zA-Z0-9 _-]/g, '').substring(0, 256);
    security = {
      id: dashId,
      name: dashName,
      description: `Security detections dashboard for ${sourceName}. Generated by Dual-Use Resource Bundles.`,
      panels,
    };
  }

  let observability: Dashboard | null = null;
  if (obsDets.length > 0) {
    const panels: DashboardPanel[] = [];
    for (const det of obsDets) {
      if (!det.criblSearchQueries) continue;
      for (const q of det.criblSearchQueries) {
        panels.push({
          id: cleanId(`obs_${det.id}_${panels.length}`),
          title: `${det.name} - ${q.name}`,
          query: q.query.replace(/\$DATASET/g, dataset),
          description: q.description || det.objective,
          type: 'search',
          earliest: '-24h',
          latest: 'now',
        });
      }
    }
    const dashId = cleanId(`dub_${sourceId}_observability`);
    const dashName = `${sourceName} - Observability`.replace(/[^a-zA-Z0-9 _-]/g, '').substring(0, 256);
    observability = {
      id: dashId,
      name: dashName,
      description: `Observability detections dashboard for ${sourceName}. Generated by Dual-Use Resource Bundles.`,
      panels,
    };
  }

  return { security, observability };
}
