import { apiUrl } from './cribl';

const DASHBOARD_BASE = () => `${apiUrl()}/m/default_search/search/dashboards`;

export interface DashboardPanel {
  id: string;
  title: string;
  query: string;
  visualization: 'table' | 'bar' | 'line' | 'pie' | 'area' | 'single';
  earliest: string;
  latest: string;
  height: number;
}

export interface DashboardRow {
  panels: DashboardPanel[];
}

export interface Dashboard {
  id: string;
  name: string;
  description?: string;
  rows: DashboardRow[];
}

export async function listDashboards(): Promise<Dashboard[]> {
  const base = DASHBOARD_BASE();
  if (!base) return [];
  const res = await fetch(base, { method: 'GET', headers: { 'Content-Type': 'application/json' } });
  if (!res.ok) return [];
  const data = await res.json();
  return data.items || data || [];
}

export async function createDashboard(dashboard: Dashboard): Promise<{ ok: boolean; status: number; message?: string }> {
  const base = DASHBOARD_BASE();
  const res = await fetch(base, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(dashboard),
  });
  if (res.ok) return { ok: true, status: res.status };
  const text = await res.text().catch(() => '');
  return { ok: false, status: res.status, message: text.substring(0, 300) };
}

export async function updateDashboard(id: string, dashboard: Dashboard): Promise<{ ok: boolean; status: number; message?: string }> {
  const base = DASHBOARD_BASE();
  const res = await fetch(`${base}/${id}`, {
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(dashboard),
  });
  if (res.ok) return { ok: true, status: res.status };
  const text = await res.text().catch(() => '');
  return { ok: false, status: res.status, message: text.substring(0, 300) };
}

export async function getDashboard(id: string): Promise<Dashboard | null> {
  const base = DASHBOARD_BASE();
  const res = await fetch(`${base}/${id}`, { method: 'GET', headers: { 'Content-Type': 'application/json' } });
  if (!res.ok) return null;
  const data = await res.json();
  return data.items?.[0] || data;
}

function chooseVisualization(query: string): 'table' | 'line' | 'bar' | 'single' {
  if (query.includes('timestats')) return 'line';
  if (query.includes('| limit 1') || /summarize\s+\w+=\w+\([^)]*\)\s*$/.test(query)) return 'single';
  if (query.includes('summarize') && query.includes(' by ')) return 'bar';
  return 'table';
}

export function buildDashboards(
  sourceName: string,
  sourceId: string,
  dataset: string,
  secDetections: any[],
  obsDetections: any[],
  enabledSecIds: Set<string>,
  enabledObsIds: Set<string>,
): { security: Dashboard | null; observability: Dashboard | null } {
  const secDets = secDetections.filter(d => enabledSecIds.has(d.id));
  const obsDets = obsDetections.filter(d => enabledObsIds.has(d.id));

  const cleanId = (s: string) => s.replace(/[^a-zA-Z0-9_]/g, '_');

  function buildRows(dets: any[], prefix: string): DashboardRow[] {
    const rows: DashboardRow[] = [];
    let panelIdx = 0;
    for (const det of dets) {
      if (!det.criblSearchQueries) continue;
      for (const q of det.criblSearchQueries) {
        const query = q.query.replace(/\$DATASET/g, dataset);
        rows.push({
          panels: [{
            id: cleanId(`${prefix}_${det.id}_${panelIdx}`),
            title: `${det.name} - ${q.name}`,
            query,
            visualization: chooseVisualization(query),
            earliest: '-24h',
            latest: 'now',
            height: 300,
          }],
        });
        panelIdx++;
      }
    }
    return rows;
  }

  let security: Dashboard | null = null;
  if (secDets.length > 0) {
    const dashId = cleanId(`dub_${sourceId}_security`);
    const dashName = `${sourceName} - Security`.replace(/[^a-zA-Z0-9 _-]/g, '').substring(0, 256);
    security = {
      id: dashId,
      name: dashName,
      description: `Security detections dashboard for ${sourceName}. Generated by Dual-Use Resource Bundles.`,
      rows: buildRows(secDets, 'sec'),
    };
  }

  let observability: Dashboard | null = null;
  if (obsDets.length > 0) {
    const dashId = cleanId(`dub_${sourceId}_observability`);
    const dashName = `${sourceName} - Observability`.replace(/[^a-zA-Z0-9 _-]/g, '').substring(0, 256);
    observability = {
      id: dashId,
      name: dashName,
      description: `Observability detections dashboard for ${sourceName}. Generated by Dual-Use Resource Bundles.`,
      rows: buildRows(obsDets, 'obs'),
    };
  }

  return { security, observability };
}
