import { apiUrl } from './cribl';

const DASHBOARD_BASE = () => `${apiUrl()}/m/default_search/search/dashboards`;

export interface DashboardElement {
  id: string;
  type: string;
  search: {
    type: 'inline';
    query: string;
    earliest: string;
    latest: string;
    timezone: string;
  };
  layout: {
    x: number;
    y: number;
    w: number;
    h: number;
  };
  config: Record<string, unknown>;
  title?: string;
}

export interface Dashboard {
  id: string;
  name: string;
  description?: string;
  schedule: {
    enabled: boolean;
    cronSchedule: string;
    tz: string;
    keepLastN: number;
  };
  groups: Record<string, unknown>;
  elements: DashboardElement[];
}

function generateShortId(): string {
  const chars = 'abcdefghijklmnopqrstuvwxyz0123456789';
  let id = '';
  for (let i = 0; i < 9; i++) id += chars[Math.floor(Math.random() * chars.length)];
  return id;
}

export async function listDashboards(): Promise<Dashboard[]> {
  const base = DASHBOARD_BASE();
  if (!base) return [];
  const res = await fetch(base, { method: 'GET', headers: { 'Content-Type': 'application/json' } });
  if (!res.ok) return [];
  const data = await res.json();
  return data.items || data || [];
}

export async function createDashboard(dashboard: Dashboard): Promise<{ ok: boolean; status: number; message?: string }> {
  const base = DASHBOARD_BASE();
  const res = await fetch(base, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(dashboard),
  });
  if (res.ok) return { ok: true, status: res.status };
  const text = await res.text().catch(() => '');
  return { ok: false, status: res.status, message: text.substring(0, 300) };
}

export async function updateDashboard(id: string, dashboard: Dashboard): Promise<{ ok: boolean; status: number; message?: string }> {
  const base = DASHBOARD_BASE();
  const res = await fetch(`${base}/${id}`, {
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(dashboard),
  });
  if (res.ok) return { ok: true, status: res.status };
  const text = await res.text().catch(() => '');
  return { ok: false, status: res.status, message: text.substring(0, 300) };
}

export async function getDashboard(id: string): Promise<Dashboard | null> {
  const base = DASHBOARD_BASE();
  const res = await fetch(`${base}/${id}`, { method: 'GET', headers: { 'Content-Type': 'application/json' } });
  if (!res.ok) return null;
  const data = await res.json();
  return data.items?.[0] || data;
}

function chooseVizType(query: string): string {
  if (query.includes('timestats')) return 'chart.line';
  if (query.includes('summarize') && query.includes(' by ')) return 'chart.column';
  return 'table';
}

export function buildDashboards(
  sourceName: string,
  _sourceId: string,
  dataset: string,
  secDetections: any[],
  obsDetections: any[],
  enabledSecIds: Set<string>,
  enabledObsIds: Set<string>,
): { security: Dashboard | null; observability: Dashboard | null } {
  const secDets = secDetections.filter(d => enabledSecIds.has(d.id));
  const obsDets = obsDetections.filter(d => enabledObsIds.has(d.id));

  function buildElements(dets: any[]): DashboardElement[] {
    const elements: DashboardElement[] = [];
    let row = 0;
    for (const det of dets) {
      if (!det.criblSearchQueries) continue;
      for (const q of det.criblSearchQueries) {
        const query = q.query.replace(/\$DATASET/g, dataset);
        elements.push({
          id: generateShortId(),
          type: chooseVizType(query),
          title: `${det.name} - ${q.name}`,
          search: {
            type: 'inline',
            query,
            earliest: '-24h',
            latest: 'now',
            timezone: 'local',
          },
          layout: {
            x: 0,
            y: row * 4,
            w: 12,
            h: 4,
          },
          config: {},
        });
        row++;
      }
    }
    return elements;
  }

  const defaultSchedule = { enabled: false, cronSchedule: '0 0 * * *', tz: 'UTC', keepLastN: 2 };

  let security: Dashboard | null = null;
  if (secDets.length > 0) {
    const dashId = generateShortId();
    const dashName = `${sourceName} - Security`.replace(/[^a-zA-Z0-9 _-]/g, '').substring(0, 256);
    security = {
      id: dashId,
      name: dashName,
      description: `Security detections dashboard for ${sourceName}. Generated by Dual-Use Resource Bundles.`,
      schedule: defaultSchedule,
      groups: {},
      elements: buildElements(secDets),
    };
  }

  let observability: Dashboard | null = null;
  if (obsDets.length > 0) {
    const dashId = generateShortId();
    const dashName = `${sourceName} - Observability`.replace(/[^a-zA-Z0-9 _-]/g, '').substring(0, 256);
    observability = {
      id: dashId,
      name: dashName,
      description: `Observability detections dashboard for ${sourceName}. Generated by Dual-Use Resource Bundles.`,
      schedule: defaultSchedule,
      groups: {},
      elements: buildElements(obsDets),
    };
  }

  return { security, observability };
}
