import fs from 'fs';

// Field matrices for all 46 missing sources
const newFields = {
  'squid-proxy': [
    { field: 'timestamp', description: 'Request timestamp', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Core timestamp' },
    { field: 'elapsed', description: 'Response time in milliseconds', securitySiem: 'No', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Performance metric' },
    { field: 'client_ip', description: 'Client source IP address', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Mask', notes: 'User identity PII' },
    { field: 'result_code', description: 'Squid result code (TCP_HIT, TCP_MISS, TCP_DENIED)', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Cache efficiency and access control' },
    { field: 'http_status', description: 'HTTP response status code', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Error rate monitoring' },
    { field: 'bytes', description: 'Response size in bytes', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Data volume tracking' },
    { field: 'method', description: 'HTTP method (GET, POST, CONNECT)', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'CONNECT indicates tunnel' },
    { field: 'url', description: 'Full request URL including query parameters', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Mask', notes: 'Browsing history PII' },
    { field: 'user', description: 'Authenticated username', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Mask', notes: 'Identity PII' },
    { field: 'peer_status', description: 'Hierarchy status (DIRECT, PARENT)', securitySiem: 'No', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'Sometimes', canMask: 'No', guardAction: 'None', notes: 'Cache hierarchy' },
    { field: 'peer_host', description: 'Upstream proxy or direct destination', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Routing path' },
    { field: 'content_type', description: 'MIME type of response', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'Sometimes', canMask: 'No', guardAction: 'None', notes: 'File type detection' },
    { field: 'host', description: 'Destination hostname', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Domain analytics' },
    { field: 'referer', description: 'HTTP Referer header', securitySiem: 'Sometimes', observability: 'No', fullFidelity: 'Yes', canDrop: 'Sometimes', canMask: 'Sometimes', guardAction: 'Mask', notes: 'May contain PII' },
    { field: 'user_agent', description: 'Client User-Agent string', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'Tag', notes: 'Bot/tool detection' },
    { field: 'category', description: 'URL category from filtering', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Content classification' },
  ],
  'aws-waf-logs': [
    { field: 'timestamp', description: 'Request timestamp in epoch ms', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Core timestamp' },
    { field: 'webaclId', description: 'Web ACL ARN', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Rule set identification' },
    { field: 'action', description: 'Action taken (ALLOW, BLOCK, COUNT, CAPTCHA)', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Enforcement decision' },
    { field: 'httpRequest_clientIp', description: 'Client source IP address', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Mask', notes: 'Attacker identification PII' },
    { field: 'httpRequest_country', description: 'Country code of client IP', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'Tag', notes: 'Geo-blocking' },
    { field: 'httpRequest_uri', description: 'Request URI path', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Mask', notes: 'Attack patterns may contain PII' },
    { field: 'httpRequest_args', description: 'Query string parameters', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Yes', guardAction: 'Mask', notes: 'SQLi/XSS payloads and credentials' },
    { field: 'httpRequest_httpMethod', description: 'HTTP method', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Method-based patterns' },
    { field: 'httpRequest_headers', description: 'Array of HTTP request headers', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Yes', guardAction: 'Redact', notes: 'Contains Auth, Cookie, API keys' },
    { field: 'terminatingRuleId', description: 'Rule ID that terminated request', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Rule effectiveness' },
    { field: 'terminatingRuleType', description: 'Rule type (REGULAR, RATE_BASED, GROUP)', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Rule category' },
    { field: 'ruleGroupList', description: 'Array of rule groups evaluated', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'Sometimes', canMask: 'No', guardAction: 'None', notes: 'Rule evaluation chain' },
    { field: 'httpSourceName', description: 'Source type (ALB, CloudFront, API Gateway)', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Origin resource type' },
    { field: 'httpSourceId', description: 'ARN of protected resource', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Resource attribution' },
    { field: 'labels', description: 'Labels applied by matching rules', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'Sometimes', canMask: 'No', guardAction: 'None', notes: 'Rule metadata' },
  ],
  'netskope': [
    { field: 'timestamp', description: 'Event timestamp', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Core timestamp' },
    { field: 'type', description: 'Event type (page, application, audit, alert)', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Event classification' },
    { field: 'srcip', description: 'Source IP address', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Mask', notes: 'Client IP PII' },
    { field: 'dstip', description: 'Destination IP address', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'Mask', notes: 'Destination server' },
    { field: 'user', description: 'Username or email', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Mask', notes: 'Identity PII' },
    { field: 'app', description: 'Cloud application name', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'SaaS usage tracking' },
    { field: 'appcategory', description: 'Application category', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Category-level policy' },
    { field: 'activity', description: 'User activity (Login, Upload, Download, Share)', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Activity classification' },
    { field: 'object', description: 'Object acted upon (file name, folder)', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Tag', notes: 'File identification' },
    { field: 'file_size', description: 'Size of file in bytes', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Exfiltration sizing' },
    { field: 'md5', description: 'MD5 hash of file', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'Sometimes', canMask: 'No', guardAction: 'None', notes: 'IOC matching' },
    { field: 'policy', description: 'DLP or access policy name', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Policy enforcement' },
    { field: 'dlp_profile', description: 'DLP profile (PCI, HIPAA, PII)', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Compliance classification' },
    { field: 'action', description: 'Action taken (alert, block, allow)', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Enforcement outcome' },
    { field: 'url', description: 'Full URL accessed', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Mask', notes: 'Browsing activity PII' },
    { field: 'from_user', description: 'Sharing source user', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Mask', notes: 'Collaboration PII' },
    { field: 'to_user', description: 'Sharing target user', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Mask', notes: 'Collaboration PII' },
    { field: 'device', description: 'Device hostname', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'Tag', notes: 'Endpoint identification' },
    { field: 'cci', description: 'Cloud Confidence Index (0-100)', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'App risk scoring' },
  ],
  'cloudflare': [
    { field: 'EdgeStartTimestamp', description: 'Timestamp when edge received request', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Core timestamp' },
    { field: 'ClientIP', description: 'Client source IP address', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Mask', notes: 'Visitor identity PII' },
    { field: 'ClientRequestHost', description: 'Hostname from Host header', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Site identification' },
    { field: 'ClientRequestURI', description: 'URI path and query string', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Mask', notes: 'May contain tokens/PII' },
    { field: 'ClientRequestMethod', description: 'HTTP method', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Request classification' },
    { field: 'EdgeResponseStatus', description: 'HTTP status returned', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Error rate monitoring' },
    { field: 'EdgeResponseBytes', description: 'Response size in bytes', securitySiem: 'No', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Bandwidth metrics' },
    { field: 'CacheCacheStatus', description: 'Cache status (hit, miss, dynamic)', securitySiem: 'No', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'Sometimes', canMask: 'No', guardAction: 'None', notes: 'Cache performance' },
    { field: 'ClientCountry', description: 'Client country code', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'Tag', notes: 'Geo analysis' },
    { field: 'ClientRequestUserAgent', description: 'User-Agent string', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'Tag', notes: 'Bot detection' },
    { field: 'OriginIP', description: 'Origin server IP', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Mask', notes: 'Infrastructure exposure' },
    { field: 'OriginResponseStatus', description: 'HTTP status from origin', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Origin health' },
    { field: 'OriginResponseTime', description: 'Time to first byte from origin (ms)', securitySiem: 'No', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Origin performance' },
    { field: 'WAFAction', description: 'WAF action (simulate, challenge, block)', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Security enforcement' },
    { field: 'WAFRuleID', description: 'WAF rule that matched', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Rule attribution' },
    { field: 'BotScore', description: 'Bot score (1=bot, 99=human)', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Bot scoring' },
    { field: 'RayID', description: 'Unique request identifier', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Request correlation' },
  ],
  'wiz-cloud-security': [
    { field: 'id', description: 'Unique finding identifier', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Finding correlation key' },
    { field: 'createdAt', description: 'Finding creation timestamp', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Core timestamp' },
    { field: 'severity', description: 'Severity (CRITICAL, HIGH, MEDIUM, LOW)', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Priority routing' },
    { field: 'status', description: 'Finding status (OPEN, RESOLVED)', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Lifecycle tracking' },
    { field: 'resource_id', description: 'Cloud resource identifier', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'Tag', notes: 'Resource identification' },
    { field: 'resource_type', description: 'Resource type (VM, Container, Storage)', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Resource classification' },
    { field: 'cloud_platform', description: 'Cloud provider (AWS, Azure, GCP)', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Multi-cloud context' },
    { field: 'subscription_id', description: 'Cloud account/subscription ID', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'Tag', notes: 'Account attribution' },
    { field: 'region', description: 'Cloud region', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Geographic context' },
    { field: 'ip_addresses', description: 'IP addresses associated with resource', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Mask', notes: 'Infrastructure topology' },
    { field: 'control_id', description: 'Security control or framework rule ID', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Compliance mapping' },
    { field: 'description', description: 'Finding description text', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Finding detail' },
    { field: 'graph_entity', description: 'Security Graph entity relationships', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'Sometimes', canMask: 'No', guardAction: 'None', notes: 'Attack path context' },
  ],
  'aws-guardduty': [
    { field: 'updatedAt', description: 'Finding last update timestamp', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Core timestamp' },
    { field: 'type', description: 'Finding type (Recon:EC2/PortProbeUnprotectedPort)', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Threat classification' },
    { field: 'severity', description: 'Severity score (0-8.9)', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Priority routing' },
    { field: 'accountId', description: 'AWS account ID', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'Tag', notes: 'Account attribution' },
    { field: 'region', description: 'AWS region', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Geographic context' },
    { field: 'resource_instanceId', description: 'EC2 instance ID', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'Tag', notes: 'Resource identification' },
    { field: 'resource_accessKeyId', description: 'IAM access key ID involved', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Yes', guardAction: 'Mask', notes: 'Credential exposure' },
    { field: 'resource_userName', description: 'IAM user or role name', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Mask', notes: 'Identity context' },
    { field: 'service_action_remoteIp', description: 'Remote IP of threat actor', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'Mask', notes: 'Attacker IP' },
    { field: 'service_action_localPort', description: 'Local port targeted', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Service identification' },
    { field: 'service_action_protocol', description: 'Network protocol', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Protocol context' },
    { field: 'service_action_domain', description: 'DNS domain queried', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'C2 domain detection' },
    { field: 'service_count', description: 'Number of times observed', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Finding frequency' },
    { field: 'title', description: 'Finding title', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Human-readable summary' },
  ],
  'google-workspace-audit': [
    { field: 'id_time', description: 'Event timestamp', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Core timestamp' },
    { field: 'actor_email', description: 'Email of acting user', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Mask', notes: 'Primary identity PII' },
    { field: 'ipAddress', description: 'IP address of the actor', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Mask', notes: 'Location PII' },
    { field: 'events_type', description: 'Event type (login, admin, drive, token)', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Event classification' },
    { field: 'events_name', description: 'Event name (create, edit, view, share)', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Action detail' },
    { field: 'events_parameters_doc_title', description: 'Document title', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Tag', notes: 'May contain sensitive names' },
    { field: 'events_parameters_target_user', description: 'Target user of share/permission change', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Mask', notes: 'Collaboration PII' },
    { field: 'events_parameters_visibility', description: 'Sharing visibility (private, domain, public)', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Data exposure risk' },
    { field: 'events_parameters_new_value', description: 'New setting value', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Tag', notes: 'Change tracking' },
    { field: 'events_parameters_oauth_app_name', description: 'OAuth application name', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Third-party app access' },
    { field: 'events_parameters_oauth_scopes', description: 'OAuth scopes granted', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'Tag', notes: 'Permission scope' },
    { field: 'ownerDomain', description: 'Google Workspace domain', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Tenant identification' },
  ],
  'microsoft-entra-id': [
    { field: 'activityDateTime', description: 'Event timestamp', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Core timestamp' },
    { field: 'userPrincipalName', description: 'User UPN (email format)', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Mask', notes: 'Primary identity PII' },
    { field: 'userDisplayName', description: 'Full display name', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Mask', notes: 'Human name PII' },
    { field: 'ipAddress', description: 'Client IP address', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Mask', notes: 'Location PII' },
    { field: 'appDisplayName', description: 'Application accessed', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'App tracking' },
    { field: 'status_errorCode', description: 'Sign-in error code (0=success)', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Auth result' },
    { field: 'conditionalAccessStatus', description: 'CA result (success, failure, notApplied)', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Policy enforcement' },
    { field: 'location_city', description: 'City from GeoIP', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Tag', notes: 'Geo PII' },
    { field: 'location_countryOrRegion', description: 'Country from GeoIP', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'Tag', notes: 'Geo context' },
    { field: 'deviceDetail_operatingSystem', description: 'Client OS', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'Sometimes', canMask: 'No', guardAction: 'None', notes: 'Device context' },
    { field: 'mfaDetail_authMethod', description: 'MFA method used', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Auth strength' },
    { field: 'riskLevel', description: 'Sign-in risk level', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Risk-based access' },
    { field: 'correlationId', description: 'Request correlation ID', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Request chain correlation' },
  ],
  'cyberark-pam': [
    { field: 'timestamp', description: 'Event timestamp', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Core timestamp' },
    { field: 'action', description: 'PAM action (Retrieve, Connect, Verify, Change)', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Action classification' },
    { field: 'user', description: 'Vault user performing action', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Mask', notes: 'Operator identity PII' },
    { field: 'safe', description: 'Vault safe name', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Access scope' },
    { field: 'target_account', description: 'Privileged account accessed', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Mask', notes: 'Credential identity' },
    { field: 'target_address', description: 'Target system hostname/IP', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Mask', notes: 'Infrastructure target' },
    { field: 'source_ip', description: 'Client IP initiating session', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Mask', notes: 'Operator location PII' },
    { field: 'reason', description: 'Business justification', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'Tag', notes: 'Access rationale' },
    { field: 'session_id', description: 'PSM session identifier', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Session correlation' },
    { field: 'session_duration', description: 'Duration in seconds', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Duration analysis' },
    { field: 'platform_id', description: 'Platform type (WinDomain, UnixSSH)', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Platform classification' },
    { field: 'status', description: 'Operation result (Success, Failure)', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Outcome tracking' },
  ],
  'microsoft-defender-endpoint': [
    { field: 'Timestamp', description: 'Event generation time', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Core timestamp' },
    { field: 'DeviceName', description: 'Endpoint hostname', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'Tag', notes: 'Device identity' },
    { field: 'ActionType', description: 'Action type (ProcessCreated, ConnectionSuccess)', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Event classification' },
    { field: 'AccountName', description: 'User account name', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Mask', notes: 'Identity PII' },
    { field: 'ProcessCommandLine', description: 'Full process command line', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Mask', notes: 'May contain credentials' },
    { field: 'InitiatingProcessCommandLine', description: 'Parent process command line', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Mask', notes: 'Process chain context' },
    { field: 'FileName', description: 'File name involved', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'File identification' },
    { field: 'FolderPath', description: 'Full file path', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'Tag', notes: 'File location' },
    { field: 'SHA256', description: 'File SHA-256 hash', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'IOC matching' },
    { field: 'RemoteIP', description: 'Remote IP for network events', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'Mask', notes: 'Network destination' },
    { field: 'LocalIP', description: 'Local device IP', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Mask', notes: 'Device network identity' },
    { field: 'RemoteUrl', description: 'Full URL for web connections', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Mask', notes: 'May contain tokens' },
    { field: 'RemotePort', description: 'Remote port', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Service identification' },
  ],
  'sentinelone-edr': [
    { field: 'createdAt', description: 'Event timestamp', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Core timestamp' },
    { field: 'agentId', description: 'Agent unique identifier', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Endpoint key' },
    { field: 'computerName', description: 'Endpoint hostname', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'Tag', notes: 'Device identity' },
    { field: 'agentIpV4', description: 'Agent IPv4 address', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Mask', notes: 'Device network location' },
    { field: 'lastLoggedInUserName', description: 'Last logged-in user', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Mask', notes: 'User identity PII' },
    { field: 'threatName', description: 'Detected threat name', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Threat classification' },
    { field: 'classification', description: 'Threat type (Malware, PUP, Exploit)', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Threat type' },
    { field: 'filePath', description: 'Full file path of threat', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'Tag', notes: 'File location' },
    { field: 'fileHash', description: 'SHA-256 hash', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'IOC matching' },
    { field: 'processCommandLine', description: 'Full process command line', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Mask', notes: 'May embed secrets' },
    { field: 'mitigationStatus', description: 'Action taken (quarantined, killed)', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Response tracking' },
    { field: 'osType', description: 'Operating system type', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Platform context' },
    { field: 'groupName', description: 'Agent group/site name', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Organizational context' },
  ],
  'proofpoint-email': [
    { field: 'ts', description: 'Event timestamp', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Core timestamp' },
    { field: 'sender', description: 'Email sender address', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Mask', notes: 'Sender PII' },
    { field: 'recipient', description: 'Email recipient address(es)', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Mask', notes: 'Recipient PII' },
    { field: 'subject', description: 'Email subject line', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Redact', notes: 'May contain sensitive content' },
    { field: 'senderIP', description: 'Sending server IP', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'Mask', notes: 'Source infrastructure' },
    { field: 'classification', description: 'Message classification (spam, phish, malware)', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Threat type' },
    { field: 'threatsInfoMap_threat', description: 'Specific threat identifier', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'IOC detail' },
    { field: 'threatsInfoMap_threatType', description: 'Threat type (url, attachment)', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Attack vector' },
    { field: 'spamScore', description: 'Spam confidence score', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Spam scoring' },
    { field: 'phishScore', description: 'Phishing confidence score', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Phish scoring' },
    { field: 'impostorScore', description: 'BEC confidence score', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'BEC detection' },
    { field: 'policyRoutes', description: 'Policy rules applied', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'Sometimes', canMask: 'No', guardAction: 'None', notes: 'Policy evaluation' },
  ],
  'mimecast-email': [
    { field: 'datetime', description: 'Event timestamp', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Core timestamp' },
    { field: 'from', description: 'Sender email address', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Mask', notes: 'Sender PII' },
    { field: 'to', description: 'Recipient email address(es)', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Mask', notes: 'Recipient PII' },
    { field: 'subject', description: 'Email subject line', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Redact', notes: 'May contain sensitive content' },
    { field: 'sender_ip', description: 'Sending server IP', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'Mask', notes: 'Source infrastructure' },
    { field: 'action', description: 'Action taken (hold, bounce, deliver)', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Delivery disposition' },
    { field: 'route', description: 'Mail route (inbound, outbound, internal)', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Direction' },
    { field: 'SpamScore', description: 'Spam confidence score', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Spam scoring' },
    { field: 'attachment_filename', description: 'Attachment file name', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Tag', notes: 'File context' },
    { field: 'attachment_sha256', description: 'Attachment SHA-256 hash', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'IOC matching' },
    { field: 'url', description: 'URL in message body', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Phishing URL' },
    { field: 'messageId', description: 'Email Message-ID header', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Message correlation' },
  ],
  'aws-alb-logs': [
    { field: 'timestamp', description: 'Request timestamp', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Core timestamp' },
    { field: 'elb', description: 'ALB resource identifier', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Load balancer identity' },
    { field: 'client_ip', description: 'Client IP address', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Mask', notes: 'Visitor PII' },
    { field: 'target_ip', description: 'Backend target IP', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'Mask', notes: 'Infrastructure IP' },
    { field: 'request_processing_time', description: 'Time from receipt to dispatch (seconds)', securitySiem: 'No', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'ALB overhead' },
    { field: 'target_processing_time', description: 'Backend response time (seconds)', securitySiem: 'No', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Primary latency metric' },
    { field: 'elb_status_code', description: 'HTTP status from ALB', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Error rate' },
    { field: 'target_status_code', description: 'HTTP status from backend', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Backend health' },
    { field: 'received_bytes', description: 'Request body size', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Upload volume' },
    { field: 'sent_bytes', description: 'Response body size', securitySiem: 'No', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Download volume' },
    { field: 'request_url', description: 'Full request URL', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Mask', notes: 'May contain tokens/PII' },
    { field: 'user_agent', description: 'Client User-Agent', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'Tag', notes: 'Bot detection' },
    { field: 'ssl_cipher', description: 'SSL cipher used', securitySiem: 'Sometimes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'Sometimes', canMask: 'No', guardAction: 'None', notes: 'Encryption compliance' },
    { field: 'target_group_arn', description: 'Target group ARN', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Backend routing' },
    { field: 'actions_executed', description: 'ALB actions executed', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Rule execution' },
  ],
  'fortinet-fortigate': [
    { field: 'date', description: 'Log date', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Core date' },
    { field: 'time', description: 'Log time', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Core time' },
    { field: 'type', description: 'Log type (traffic, utm, event)', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Event classification' },
    { field: 'subtype', description: 'Log subtype (forward, local)', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Sub-classification' },
    { field: 'srcip', description: 'Source IP address', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Mask', notes: 'Source host PII' },
    { field: 'dstip', description: 'Destination IP address', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Mask', notes: 'Destination host' },
    { field: 'srcport', description: 'Source port', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Connection detail' },
    { field: 'dstport', description: 'Destination port', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Service identification' },
    { field: 'action', description: 'Action (accept, deny, close)', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Policy enforcement' },
    { field: 'user', description: 'Authenticated user name', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Mask', notes: 'Identity PII' },
    { field: 'policyid', description: 'Firewall policy ID', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Policy attribution' },
    { field: 'sentbyte', description: 'Bytes sent', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Volume' },
    { field: 'rcvdbyte', description: 'Bytes received', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Volume' },
    { field: 'duration', description: 'Session duration in seconds', securitySiem: 'No', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Session timing' },
    { field: 'app', description: 'Application identified', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'App visibility' },
    { field: 'devname', description: 'FortiGate hostname', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Device identity' },
  ],
  'cisco-firepower': [
    { field: 'timestamp', description: 'Event timestamp', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Core timestamp' },
    { field: 'InitiatorIP', description: 'Source/Initiator IP', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Mask', notes: 'Source host' },
    { field: 'ResponderIP', description: 'Destination/Responder IP', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Mask', notes: 'Destination host' },
    { field: 'InitiatorPort', description: 'Source port', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Source port' },
    { field: 'ResponderPort', description: 'Destination port', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Service identification' },
    { field: 'Protocol', description: 'IP protocol (TCP, UDP)', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Protocol context' },
    { field: 'User', description: 'Identity-mapped username', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Mask', notes: 'Identity PII' },
    { field: 'AccessControlRuleName', description: 'Rule that matched', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Policy attribution' },
    { field: 'AccessControlRuleAction', description: 'Rule action (Allow, Block)', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Enforcement decision' },
    { field: 'Application', description: 'Application identified', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Application visibility' },
    { field: 'URL', description: 'URL for HTTP events', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Mask', notes: 'Browsing PII' },
    { field: 'InitiatorBytes', description: 'Bytes sent by initiator', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Volume analysis' },
    { field: 'ResponderBytes', description: 'Bytes by responder', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Volume analysis' },
    { field: 'DNSQuery', description: 'DNS query name', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'Tag', notes: 'Domain visibility' },
  ],
  'juniper-srx': [
    { field: 'timestamp', description: 'Event timestamp', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Core timestamp' },
    { field: 'source_address', description: 'Source IP', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Mask', notes: 'Source host' },
    { field: 'destination_address', description: 'Destination IP', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Mask', notes: 'Destination host' },
    { field: 'nat_source_address', description: 'NAT translated source IP', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'Sometimes', canMask: 'No', guardAction: 'Mask', notes: 'NAT translation' },
    { field: 'source_port', description: 'Source port', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Connection detail' },
    { field: 'destination_port', description: 'Destination port', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Service identification' },
    { field: 'protocol_id', description: 'IP protocol number', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Protocol context' },
    { field: 'policy_name', description: 'Security policy name', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Policy attribution' },
    { field: 'source_zone_name', description: 'Source security zone', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Zone context' },
    { field: 'destination_zone_name', description: 'Destination zone', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Zone context' },
    { field: 'session_id', description: 'Flow session ID', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Session correlation' },
    { field: 'bytes_from_client', description: 'Bytes from client', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Volume' },
    { field: 'bytes_from_server', description: 'Bytes from server', securitySiem: 'Yes', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Volume' },
    { field: 'elapsed_time', description: 'Session duration', securitySiem: 'No', observability: 'Yes', fullFidelity: 'Yes', canDrop: 'No', canMask: 'No', guardAction: 'None', notes: 'Duration' },
    { field: 'username', description: 'Authenticated user', securitySiem: 'Yes', observability: 'No', fullFidelity: 'Yes', canDrop: 'No', canMask: 'Sometimes', guardAction: 'Mask', notes: 'Identity PII' },
  ],
};

// Read existing file and insert before closing };
let content = fs.readFileSync('src/data/fields.ts', 'utf8');
const insertPoint = content.lastIndexOf('};');

let newContent = '';
for (const [sourceId, fields] of Object.entries(newFields)) {
  newContent += `,\n  '${sourceId}': [\n`;
  fields.forEach((f, i) => {
    const desc = f.description.replace(/'/g, "\\'");
    const notes = f.notes.replace(/'/g, "\\'");
    newContent += `    { field: '${f.field}', description: '${desc}', securitySiem: '${f.securitySiem}', observability: '${f.observability}', fullFidelity: '${f.fullFidelity}', canDrop: '${f.canDrop}', canMask: '${f.canMask}', guardAction: '${f.guardAction}', notes: '${notes}' }${i < fields.length - 1 ? ',' : ''}\n`;
  });
  newContent += '  ]';
}

content = content.slice(0, insertPoint - 1) + newContent + '\n};\n';
fs.writeFileSync('src/data/fields.ts', content);
console.log('Batch 1 complete: Added', Object.keys(newFields).length, 'source field matrices');
